### ISSUE TITLE
Q: update several a records at the same time

### ISSUE THREAD

**Issue by smycek** [rmarchant/gandi-ddns#12]
I'm looking for a way to update several DNS records that differ from the type at the same time.
I have two questions about this:

1.) Is it possible to update several A-Records (Domain & Subdomains) at the same time by storing several, separated entries at "a_name" in the config.txt? If that works, which separator should be used?

2.) In order to properly configure my mail server I also need to update a TXT-Record ("v=spf1 a mx ip4: <ipv4 address> -all") regularly and plan to extend the script for this task. Do I have to pay special attention or can I simply extend the script with a suitable method?

Thank you for your time and work!

**Comment by rmarchant** [comment]
Hello @smycek, 

1). No, but if you're updating an A record for your domain, then you can just use CNAME records for the subdomains that point to the host with the A record. For example, if your domain was 'example.com', your zone file would look like:
```
@ 300 IN A 111.111.111.111
www 300 IN CNAME example.com.
dev 300 IN CNAME example.com.
```
So when the @ A record is updated via the script, the change is automatically reflected in the CNAME records pointing to that host.

2). You can extend the script however you'd like :) I do not plan on incorporating TXT/SPF record updates.

3). You're very welcome!
