### ISSUE TITLE
2 sub domains to update

### ISSUE THREAD

**Issue by antonio-nuzzo** [rmarchant/gandi-ddns#16]
Hi,
The script works fine, thanx. 
What if I want to update 2 subdomains ? Do I have to copy the script and the config file in 2 directories? I tried a comma and a space separator but got error messages.

Thanx in advance

**Comment by rmarchant** [comment]
Hello, 

I would suggest using a CNAME record to point one sub-domain to the other sub-domain.

Example:

Setup script to update foo.example.com.

Then create a CNAME DNS record pointing foo2.example.com to foo.example.com

foo2 3600 IN CNAME foo.example.com.

That way when foo.example.com is updated, foo2 will also point to the same IP via the CNAME record.
