### ISSUE TITLE
Script not working as cron job

### ISSUE THREAD

**Issue by eldelacajita** [rmarchant/gandi-ddns#9]
Hi @rmarchant. First, thanks a lot for creating this script, it's really useful. I'm just finding an issue when using it via cron.

Once the config file is setup, I can execute the command with 
`python /home/user/Software/gandi-ddns/gandi_ddns.py` 
and everything works perfectly. I can see the IP is being updated in the Gandi admin panel. 

Then I add it as a cron job, with this format:
`*/15 * * * * python /home/user/Software/gandi-ddns/gandi_ddns.py` 

I can tell it's being run by looking into `/var/log/syslog` and seeing lines like this one:
`Sep 25 20:44:01 devicename CRON[5733]: (root) CMD (python /home/user/Software/gandi-ddns/gandi_ddns.py)`

But the DNS records are _not_ being updated in the Gandi admin panel anymore. Is there something else I should take into account when configuring crontab?

**Comment by rmarchant** [comment]
Hello @eldelacajita,

I suggest that you try putting the full path to your python binary in the cron task. For example :

`*/15 * * * *  /usr/bin/python2.7 /home/user/Software/gandi-ddns/gandi_ddns.py`

(Modify the path to match where your python binary is located on your system)

**Comment by eldelacajita** [comment]
That solved it, now it's up and running :)
Thanks for the tip, and for sharing the script!
